// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationmaster_protocol.proto

#ifndef PROTOBUF_applicationmaster_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_applicationmaster_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include "yarn_service_protos.pb.h"
// @@protoc_insertion_point(includes)

namespace hadoop {
namespace yarn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_applicationmaster_5fprotocol_2eproto();
void protobuf_AssignDesc_applicationmaster_5fprotocol_2eproto();
void protobuf_ShutdownFile_applicationmaster_5fprotocol_2eproto();


// ===================================================================


// ===================================================================

class ApplicationMasterProtocolService_Stub;

class ApplicationMasterProtocolService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline ApplicationMasterProtocolService() {};
 public:
  virtual ~ApplicationMasterProtocolService();

  typedef ApplicationMasterProtocolService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void registerApplicationMaster(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::RegisterApplicationMasterRequestProto* request,
                       ::hadoop::yarn::RegisterApplicationMasterResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void finishApplicationMaster(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::FinishApplicationMasterRequestProto* request,
                       ::hadoop::yarn::FinishApplicationMasterResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void allocate(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::AllocateRequestProto* request,
                       ::hadoop::yarn::AllocateResponseProto* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ApplicationMasterProtocolService);
};

class ApplicationMasterProtocolService_Stub : public ApplicationMasterProtocolService {
 public:
  ApplicationMasterProtocolService_Stub(::google::protobuf::RpcChannel* channel);
  ApplicationMasterProtocolService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~ApplicationMasterProtocolService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements ApplicationMasterProtocolService ------------------------------------------

  void registerApplicationMaster(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::RegisterApplicationMasterRequestProto* request,
                       ::hadoop::yarn::RegisterApplicationMasterResponseProto* response,
                       ::google::protobuf::Closure* done);
  void finishApplicationMaster(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::FinishApplicationMasterRequestProto* request,
                       ::hadoop::yarn::FinishApplicationMasterResponseProto* response,
                       ::google::protobuf::Closure* done);
  void allocate(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::AllocateRequestProto* request,
                       ::hadoop::yarn::AllocateResponseProto* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ApplicationMasterProtocolService_Stub);
};


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace yarn
}  // namespace hadoop

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_applicationmaster_5fprotocol_2eproto__INCLUDED
