// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationclient_protocol.proto

#ifndef PROTOBUF_applicationclient_5fprotocol_2eproto__INCLUDED
#define PROTOBUF_applicationclient_5fprotocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include "Security.pb.h"
#include "yarn_service_protos.pb.h"
// @@protoc_insertion_point(includes)

namespace hadoop {
namespace yarn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_applicationclient_5fprotocol_2eproto();
void protobuf_AssignDesc_applicationclient_5fprotocol_2eproto();
void protobuf_ShutdownFile_applicationclient_5fprotocol_2eproto();


// ===================================================================


// ===================================================================

class ApplicationClientProtocolService_Stub;

class ApplicationClientProtocolService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline ApplicationClientProtocolService() {};
 public:
  virtual ~ApplicationClientProtocolService();

  typedef ApplicationClientProtocolService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void getNewApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetNewApplicationRequestProto* request,
                       ::hadoop::yarn::GetNewApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getApplicationReport(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetApplicationReportRequestProto* request,
                       ::hadoop::yarn::GetApplicationReportResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void submitApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::SubmitApplicationRequestProto* request,
                       ::hadoop::yarn::SubmitApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void forceKillApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::KillApplicationRequestProto* request,
                       ::hadoop::yarn::KillApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getClusterMetrics(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetClusterMetricsRequestProto* request,
                       ::hadoop::yarn::GetClusterMetricsResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getApplications(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetApplicationsRequestProto* request,
                       ::hadoop::yarn::GetApplicationsResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getClusterNodes(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetClusterNodesRequestProto* request,
                       ::hadoop::yarn::GetClusterNodesResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getQueueInfo(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetQueueInfoRequestProto* request,
                       ::hadoop::yarn::GetQueueInfoResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getQueueUserAcls(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetQueueUserAclsInfoRequestProto* request,
                       ::hadoop::yarn::GetQueueUserAclsInfoResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void getDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::GetDelegationTokenRequestProto* request,
                       ::hadoop::common::GetDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void renewDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::RenewDelegationTokenRequestProto* request,
                       ::hadoop::common::RenewDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);
  virtual void cancelDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::CancelDelegationTokenRequestProto* request,
                       ::hadoop::common::CancelDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ApplicationClientProtocolService);
};

class ApplicationClientProtocolService_Stub : public ApplicationClientProtocolService {
 public:
  ApplicationClientProtocolService_Stub(::google::protobuf::RpcChannel* channel);
  ApplicationClientProtocolService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~ApplicationClientProtocolService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements ApplicationClientProtocolService ------------------------------------------

  void getNewApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetNewApplicationRequestProto* request,
                       ::hadoop::yarn::GetNewApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getApplicationReport(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetApplicationReportRequestProto* request,
                       ::hadoop::yarn::GetApplicationReportResponseProto* response,
                       ::google::protobuf::Closure* done);
  void submitApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::SubmitApplicationRequestProto* request,
                       ::hadoop::yarn::SubmitApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  void forceKillApplication(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::KillApplicationRequestProto* request,
                       ::hadoop::yarn::KillApplicationResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getClusterMetrics(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetClusterMetricsRequestProto* request,
                       ::hadoop::yarn::GetClusterMetricsResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getApplications(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetApplicationsRequestProto* request,
                       ::hadoop::yarn::GetApplicationsResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getClusterNodes(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetClusterNodesRequestProto* request,
                       ::hadoop::yarn::GetClusterNodesResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getQueueInfo(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetQueueInfoRequestProto* request,
                       ::hadoop::yarn::GetQueueInfoResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getQueueUserAcls(::google::protobuf::RpcController* controller,
                       const ::hadoop::yarn::GetQueueUserAclsInfoRequestProto* request,
                       ::hadoop::yarn::GetQueueUserAclsInfoResponseProto* response,
                       ::google::protobuf::Closure* done);
  void getDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::GetDelegationTokenRequestProto* request,
                       ::hadoop::common::GetDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);
  void renewDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::RenewDelegationTokenRequestProto* request,
                       ::hadoop::common::RenewDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);
  void cancelDelegationToken(::google::protobuf::RpcController* controller,
                       const ::hadoop::common::CancelDelegationTokenRequestProto* request,
                       ::hadoop::common::CancelDelegationTokenResponseProto* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ApplicationClientProtocolService_Stub);
};


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace yarn
}  // namespace hadoop

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_applicationclient_5fprotocol_2eproto__INCLUDED
